class CaseTypes
	def excluded
		[
			'Small Claims - General',
			'Domestic Relations Dissolution',
			'Domestic Relations Petition Custody',
			'Domestic Relations Abuse Prevention',
			'Domestic Relations Elder Abuse',
			'Domestic Relations Financial Responsibility',
			'Appeal from Justice Court',
			'Dissolution',
			'Separation',
			'Annulment',
			'Administrative - Civil',
			'Review - Gun Permit Appeal',
			'Post-Conviction',
			'Post Conviction Relief',
			'Constitutional Writs - Habeas Corpus',
			'Filiation',
			'Money Action',
			'Small Claims Contract',
			'Document Recording',
			'Estate',
			'Stalking',
			'Document Recording - Civil',
			'Landlord/Tenant - Residential',
			'Landlord/Tenant - General',
			'Identity Record',
			'Property - General',
			'Small Estate',
			'Forcible Entry Detainer: Residential',
			'Procedural Matters - Material Witness Hold',
			'Property - Foreclosure',
			'Foreclosure',
			'Other',
			'Name Change',
			'Forfeiture',
			'Document Recording - Family',
			'Petition Custody/Support/Visitation',
			'Minor Protective Proceedings',
			'Adult Protective Proceedings',
			'Protective Order - Stalking',
			'Review - Government Actions',
			'Trust',
			'Register Foreign Judgment',
			'Estate - General',
			'Injunctive Relief',
			'Protective Order - FAPA',
			'Protective Order - Elder Abuse',
			'Protective Order - Sexual Abuse',
			'Procedural Matters - General',
			'Procedural Matters - Relief From Sex Offender Registration',
			'Procedural Matters - Set Aside Arrest Record'
		]
	end
end
