class Parties
	def excluded
		[
			'Acctcorp International of Salem',
			'Ally Bank',
			'Ally Financial Inc.',
			'AMERICAN EXPRESS BANK FSB',
			'American Express Bank, FSB',
			'American Express Centurion Bank',
			'American Express Bank, Fsb',
			'Asset Recovery Group, Inc.',
			'Asset Systems, Inc.',
			'Automax Financial LLC',
			'Bank of America, N.A.',
			'Bank of America NA',
			'Barclays Bank Delaware',
			'Bonneville Billing & Collections, Inc.',
			'Brandt Financial Services, Inc.',
			'Capital One, N.A.',
			'Capital One Bank (USA),N.A.',
			'Capital One Bank (USA), N.A.',
			'Capital One Bank (USA) NA',
			'Capital One Bank (Usa), N.a.',
			'CAPITAL ONE BANK USA NA',
			'Cavalry SPV I LLC',
			'Cavalry SPV I, LLC',
			'Calvary SPV I LLC',
			'CAVALRY SPV I LLC',
			'Central Willamette Community Credit Union',
			'Citibank NA',
			'CITIBANK NA',
			'Citibank, N.A.',
			'Credit Acceptance Corporation',
			'Credit Corp Solutions, Inc.',
			'Crown Asset Management, LLC',
			'CSO Financial, Inc.',
			'Department Stores National Bank',
			'Discover Bank',
			'DISCOVER BANK',
			'Diverse Funding Associates, LLC',
			'DolEx Dollar Express, Inc.',
			'Evergreen Professional Recoveries, Inc.',
			'First National Bank of Omaha',
			'First Technology Federal Credit Union',
			'Ford Motor Credit Company LLC',
			'Ford Motor Company LLC',
			'Foxwood Financial L.L.C.',
			'Foxwood Financial, LLC',
			'Icon Equities, LLC',
			'Jefferson Capital Systems, LLC',
			'LCS Financial Services Corporation',
			'LVNV Funding LLC',
			'LVNV FUNDING LLC',
			'Lvnv Funding Llc',
			'Mckenzie-Willamette Regional Medical Center',
			'McKenzie-Willamette Regional Medical Center Associates, LLC',
			'Midland Credit Management, Inc.',
			'Midland Funding',
			'Midland Funding, LLC',
			'Midland Funding LLC',
			'MSW Capital, LLC',
			'National Collegiate Student Loan Trust 2004-1, A Delaware Statutory Trust(s)',
			'OneMain Financial, Inc.',
			'OneMain Financial Group, LLC',
			'OneMain Financial Services, Inc.',
			'Oregon State Credit Union',
			'Pioneer Services, A Division of Midcountry Bank',
			'Portland Credit, Inc.',
			'Portfolio Recovery Associates, LLC',
			'Portfolio Recovery Associates LLC',
			'Portfolio Recovery Associates, Llc',
			'Portrfolio Recovery Associates, LLC ',
			'Portfolio Recovery Associates LLC',
			'Private Capital Group, Inc.',
			'Ray Klein Inc',
			'Ray Klein, Inc.',
			'Second Round, LP',
			'Second Round LP',
			'Second Round Sub, LLC',
			'SELCO Community Credit Union',
			'Southern Oregon Credit Service Inc',
			'Southern Oregon Credit Service, Inc.',
			'State Farm Bank',
			'Synchrony Bank',
			'TBF Financial, LLC',
			'TD Bank USA, N.A.',
			'Unifund CCR, LLC',
			'United Community Credit Union',
			'United Auto Credit Corporation',
			'Valley Credit Service Inc',
			'Velocity Investments, LLC',
			'Wauna Credit Union',
			'We Collect Inc',
			'Wells Fargo Bank, N.A',
			'Western Mercantile Agency Inc.'
		]
	end
end
